# Data Source

I'm using weekly fantasy football data downloaded from [FantasyPros](https://www.fantasypros.com/). Specifically, I downloaded weekly data by position with the settings of Half PPR and Consensus Roster %. You can access an example week [here](https://www.fantasypros.com/nfl/stats/qb.php?week=1&scoring=HALF&range=week).

# Load in libraries

In [22]:
import pandas as pd
import numpy as np

# Set file path for each position

In [2]:
qb_path = 'C:\\Users\\Lenovo\\OneDrive\\Desktop\\fantasy_football\\2023\\QB_'
rb_path = 'C:\\Users\\Lenovo\\OneDrive\\Desktop\\fantasy_football\\2023\\RB_'
wr_path = 'C:\\Users\\Lenovo\\OneDrive\\Desktop\\fantasy_football\\2023\\WR_'
te_path = 'C:\\Users\\Lenovo\\OneDrive\\Desktop\\fantasy_football\\2023\\TE_'

# Load in weekly data

## QBs

In [3]:
qb1 = pd.read_csv(qb_path+'1.csv')
qb2 = pd.read_csv(qb_path+'2.csv')
qb3 = pd.read_csv(qb_path+'3.csv')
qb4 = pd.read_csv(qb_path+'4.csv')
qb5 = pd.read_csv(qb_path+'5.csv')
qb6 = pd.read_csv(qb_path+'6.csv')
qb7 = pd.read_csv(qb_path+'7.csv')
qb8 = pd.read_csv(qb_path+'8.csv')
qb9 = pd.read_csv(qb_path+'9.csv')
qb10 = pd.read_csv(qb_path+'10.csv')
qb11 = pd.read_csv(qb_path+'11.csv')
qb12 = pd.read_csv(qb_path+'12.csv')
qb13 = pd.read_csv(qb_path+'13.csv')
qb14 = pd.read_csv(qb_path+'14.csv')
qb15 = pd.read_csv(qb_path+'15.csv')
qb16 = pd.read_csv(qb_path+'16.csv')
qb17 = pd.read_csv(qb_path+'17.csv')
qb18 = pd.read_csv(qb_path+'18.csv')

## RBs

In [4]:
rb1 = pd.read_csv(rb_path+'1.csv')
rb2 = pd.read_csv(rb_path+'2.csv')
rb3 = pd.read_csv(rb_path+'3.csv')
rb4 = pd.read_csv(rb_path+'4.csv')
rb5 = pd.read_csv(rb_path+'5.csv')
rb6 = pd.read_csv(rb_path+'6.csv')
rb7 = pd.read_csv(rb_path+'7.csv')
rb8 = pd.read_csv(rb_path+'8.csv')
rb9 = pd.read_csv(rb_path+'9.csv')
rb10 = pd.read_csv(rb_path+'10.csv')
rb11 = pd.read_csv(rb_path+'11.csv')
rb12 = pd.read_csv(rb_path+'12.csv')
rb13 = pd.read_csv(rb_path+'13.csv')
rb14 = pd.read_csv(rb_path+'14.csv')
rb15 = pd.read_csv(rb_path+'15.csv')
rb16 = pd.read_csv(rb_path+'16.csv')
rb17 = pd.read_csv(rb_path+'17.csv')
rb18 = pd.read_csv(rb_path+'18.csv')

## WRs

In [5]:
wr1 = pd.read_csv(wr_path+'1.csv')
wr2 = pd.read_csv(wr_path+'2.csv')
wr3 = pd.read_csv(wr_path+'3.csv')
wr4 = pd.read_csv(wr_path+'4.csv')
wr5 = pd.read_csv(wr_path+'5.csv')
wr6 = pd.read_csv(wr_path+'6.csv')
wr7 = pd.read_csv(wr_path+'7.csv')
wr8 = pd.read_csv(wr_path+'8.csv')
wr9 = pd.read_csv(wr_path+'9.csv')
wr10 = pd.read_csv(wr_path+'10.csv')
wr11 = pd.read_csv(wr_path+'11.csv')
wr12 = pd.read_csv(wr_path+'12.csv')
wr13 = pd.read_csv(wr_path+'13.csv')
wr14 = pd.read_csv(wr_path+'14.csv')
wr15 = pd.read_csv(wr_path+'15.csv')
wr16 = pd.read_csv(wr_path+'16.csv')
wr17 = pd.read_csv(wr_path+'17.csv')
wr18 = pd.read_csv(wr_path+'18.csv')

## TEs

In [6]:
te1 = pd.read_csv(te_path+'1.csv')
te2 = pd.read_csv(te_path+'2.csv')
te3 = pd.read_csv(te_path+'3.csv')
te4 = pd.read_csv(te_path+'4.csv')
te5 = pd.read_csv(te_path+'5.csv')
te6 = pd.read_csv(te_path+'6.csv')
te7 = pd.read_csv(te_path+'7.csv')
te8 = pd.read_csv(te_path+'8.csv')
te9 = pd.read_csv(te_path+'9.csv')
te10 = pd.read_csv(te_path+'10.csv')
te11 = pd.read_csv(te_path+'11.csv')
te12 = pd.read_csv(te_path+'12.csv')
te13 = pd.read_csv(te_path+'13.csv')
te14 = pd.read_csv(te_path+'14.csv')
te15 = pd.read_csv(te_path+'15.csv')
te16 = pd.read_csv(te_path+'16.csv')
te17 = pd.read_csv(te_path+'17.csv')
te18 = pd.read_csv(te_path+'18.csv')

# Create list of weekly dataframes by position

In [7]:
qb_dfs = [qb1, qb2, qb3, qb4, qb5, qb6,
          qb7, qb8, qb9, qb10, qb11, qb12,
          qb13, qb14, qb15, qb16, qb17, qb18]

rb_dfs = [rb1, rb2, rb3, rb4, rb5, rb6,
          rb7, rb8, rb9, rb10, rb11, rb12,
          rb13, rb14, rb15, rb16, rb17, rb18]

wr_dfs = [wr1, wr2, wr3, wr4, wr5, wr6,
          wr7, wr8, wr9, wr10, wr11, wr12,
          wr13, wr14, wr15, wr16, wr17, wr18]

te_dfs = [te1, te2, te3, te4, te5, te6,
          te7, te8, te9, te10, te11, te12,
          te13, te14, te15, te16, te17, te18]

# Add 'WK' column

In [8]:
for i in range(len(qb_dfs)):
    qb_dfs[i]['WK'] = i+1
    rb_dfs[i]['WK'] = i+1
    wr_dfs[i]['WK'] = i+1
    te_dfs[i]['WK'] = i+1

# Create one dataframe per position

In [9]:
qb = pd.concat(qb_dfs)
rb = pd.concat(rb_dfs)
wr = pd.concat(wr_dfs)
te = pd.concat(te_dfs)

# Clean up dataframes

## Drop rows with mostly NAs

In [10]:
qb = qb.dropna()
rb = rb.dropna()
wr = wr.dropna()
te = te.dropna()

## Drop unnecessary columns

In [11]:
qb = qb.drop(['G', 'FPTS/G', 'ROST'], axis=1)
rb = rb.drop(['G', 'FPTS/G', 'ROST'], axis=1)
wr = wr.drop(['G', 'FPTS/G', 'ROST'], axis=1)
te = te.drop(['G', 'FPTS/G', 'ROST'], axis=1)

## Remove teams from player names

In [12]:
for i in range(len(qb)):
    qb['Player'].iat[i] = qb['Player'].iat[i].split(' (', 1)[0]
    
for i in range(len(rb)):
    rb['Player'].iat[i] = rb['Player'].iat[i].split(' (', 1)[0]
    
for i in range(len(wr)):
    wr['Player'].iat[i] = wr['Player'].iat[i].split(' (', 1)[0]
    
for i in range(len(te)):
    te['Player'].iat[i] = te['Player'].iat[i].split(' (', 1)[0]

# WAR

WAR stands for "Wins Above Replacement." The idea is to determine how many more/fewer wins a player contributed to their team relative to a replacement-level player. To do this, we need to figure out the following info:
1. Average weekly score in my league
2. Average team score standard deviation
3. Calculate replacement-level player for each position
4. Determine each player's WAR

In [38]:
n_teams=12

## Average weekly score

## Average team score standard deviation

## Weekly replacement-level player by position

### QB

In [39]:
qb_replacements = qb[(qb['Rank'] > n_teams) & (qb['Rank'] <= n_teams*2)]

In [40]:
qb_wkly_rep_score = np.zeros(18)

for i in range(len(qb_wkly_rep_score)):
    qb_wkly_rep_score[i] = qb_replacements[qb_replacements['WK'] == i+1]['FPTS'].mean()

In [41]:
qb_wkly_rep_score

array([16.275     , 14.75833333, 14.675     , 15.13333333, 13.825     ,
       12.625     , 12.425     , 16.03333333, 12.54166667, 16.20833333,
       12.83333333, 15.41666667, 14.65833333, 12.85      , 13.85      ,
       13.05      , 12.46666667, 11.81666667])

### RB

In [42]:
rb_replacements = rb[(rb['Rank'] > n_teams*2) & (rb['Rank'] <= n_teams*4)]

In [43]:
rb_wkly_rep_score = np.zeros(18)

for i in range(len(rb_wkly_rep_score)):
    rb_wkly_rep_score[i] = rb_replacements[rb_replacements['WK'] == i+1]['FPTS'].mean()

In [44]:
rb_wkly_rep_score

array([7.6875    , 6.61666667, 7.03333333, 7.61666667, 7.62916667,
       4.78333333, 6.65416667, 7.45416667, 4.28333333, 5.89166667,
       5.41666667, 7.94166667, 6.775     , 4.9375    , 8.05833333,
       6.1875    , 6.9125    , 6.34583333])

### WR

In [45]:
wr_replacements = wr[(wr['Rank'] > n_teams*2) & (wr['Rank'] <= n_teams*4)]

In [46]:
wr_wkly_rep_score = np.zeros(18)

for i in range(len(wr_wkly_rep_score)):
    wr_wkly_rep_score[i] = wr_replacements[wr_replacements['WK'] == i+1]['FPTS'].mean()

In [47]:
wr_wkly_rep_score

array([ 9.75833333, 10.0875    , 10.64166667,  8.65833333,  8.74583333,
        8.61666667,  8.6375    ,  9.35416667,  5.7125    ,  9.52083333,
        8.65833333,  9.77916667,  9.27916667,  9.09583333,  9.54583333,
        8.96666667,  6.70833333,  8.75416667])

### TE

In [48]:
te_replacements = te[(te['Rank'] > n_teams) & (te['Rank'] <= n_teams*2)]

In [49]:
te_wkly_rep_score = np.zeros(18)

for i in range(len(te_wkly_rep_score)):
    te_wkly_rep_score[i] = te_replacements[te_replacements['WK'] == i+1]['FPTS'].mean()

In [50]:
te_wkly_rep_score

array([6.225     , 6.11666667, 6.03333333, 6.34166667, 6.04166667,
       6.93333333, 6.11666667, 6.5       , 5.25833333, 5.025     ,
       4.41666667, 5.95833333, 4.68333333, 3.78333333, 7.19166667,
       6.31666667, 8.4       , 6.3       ])

### FLEX

This is a bit harder to calculate since the FLEX position could be a RB, WR, or TE. I'll assume the FLEX starters are the top 12-highest scores after the top 24 RBs, top 24 WRs, and top 12 TEs are removed, and the replacement-level FLEX players are the next 12 highest scorers.

In [63]:
rb_narrow = rb[['Rank', 'Player', 'FPTS', 'WK']].copy()
wr_narrow = wr[['Rank', 'Player', 'FPTS', 'WK']].copy()
te_narrow = te[['Rank', 'Player', 'FPTS', 'WK']].copy()

In [64]:
rb_narrow['POS'] = 'RB'
wr_narrow['POS'] = 'WR'
te_narrow['POS'] = 'TE'

In [87]:
flex = pd.concat([rb_narrow, wr_narrow, te_narrow])

In [94]:
flex.head()

Rank          Player  FPTS  WK POS
24  25.0  Brandon Bolden   9.8   1  RB
25  26.0    Najee Harris   9.6   1  RB
26  27.0    Rex Burkhead   9.5   1  RB
27  28.0   Austin Ekeler   9.2   1  RB
28  29.0     Aaron Jones   9.1   1  RB

In [88]:
# Removing starting RBs, WRs, and TEs
flex = flex[((flex['POS'] == 'RB') & (flex['Rank'] > 24)) |
            ((flex['POS'] == 'WR') & (flex['Rank'] > 24)) |
            ((flex['POS'] == 'TE') & (flex['Rank'] > 12))]

In [95]:
flex = flex.sort_values(['WK', 'FPTS'], ascending=False)

In [98]:
flex['Rank'] = flex.groupby(['WK']).cumcount()+1

In [106]:
flex_replacements = flex[(flex['Rank'] > n_teams) & (flex['Rank'] <=n_teams*2)]

In [107]:
flex_wkly_rep_score = np.zeros(18)

for i in range(len(flex_wkly_rep_score)):
    flex_wkly_rep_score[i] = flex_replacements[flex_replacements['WK'] == i+1]['FPTS'].mean()

In [108]:
flex_wkly_rep_score

array([ 9.125     ,  8.925     , 10.01666667,  8.99166667,  8.89166667,
        7.775     ,  8.475     ,  9.20833333,  5.98333333,  8.625     ,
        8.04166667,  9.61666667,  8.7       ,  7.90833333,  9.91666667,
        8.54166667,  7.99166667,  7.95833333])

## Individual Player WAR