# Data Source

I'm using weekly fantasy football data downloaded from [FantasyPros](https://www.fantasypros.com/). Specifically, I downloaded weekly data by position with the settings of Half PPR and Consensus Roster %. You can access an example week [here](https://www.fantasypros.com/nfl/stats/qb.php?week=1&scoring=HALF&range=week).

# Load in libraries

In [74]:
import pandas as pd
import numpy as np
import scipy.stats as st

# Set file path for each position

In [2]:
qb_path = 'C:\\Users\\Lenovo\\OneDrive\\Desktop\\fantasy_football\\2023\\QB_'
rb_path = 'C:\\Users\\Lenovo\\OneDrive\\Desktop\\fantasy_football\\2023\\RB_'
wr_path = 'C:\\Users\\Lenovo\\OneDrive\\Desktop\\fantasy_football\\2023\\WR_'
te_path = 'C:\\Users\\Lenovo\\OneDrive\\Desktop\\fantasy_football\\2023\\TE_'

# Load in weekly data

## QBs

In [3]:
qb1 = pd.read_csv(qb_path+'1.csv')
qb2 = pd.read_csv(qb_path+'2.csv')
qb3 = pd.read_csv(qb_path+'3.csv')
qb4 = pd.read_csv(qb_path+'4.csv')
qb5 = pd.read_csv(qb_path+'5.csv')
qb6 = pd.read_csv(qb_path+'6.csv')
qb7 = pd.read_csv(qb_path+'7.csv')
qb8 = pd.read_csv(qb_path+'8.csv')
qb9 = pd.read_csv(qb_path+'9.csv')
qb10 = pd.read_csv(qb_path+'10.csv')
qb11 = pd.read_csv(qb_path+'11.csv')
qb12 = pd.read_csv(qb_path+'12.csv')
qb13 = pd.read_csv(qb_path+'13.csv')
qb14 = pd.read_csv(qb_path+'14.csv')
qb15 = pd.read_csv(qb_path+'15.csv')
qb16 = pd.read_csv(qb_path+'16.csv')
qb17 = pd.read_csv(qb_path+'17.csv')

## RBs

In [4]:
rb1 = pd.read_csv(rb_path+'1.csv')
rb2 = pd.read_csv(rb_path+'2.csv')
rb3 = pd.read_csv(rb_path+'3.csv')
rb4 = pd.read_csv(rb_path+'4.csv')
rb5 = pd.read_csv(rb_path+'5.csv')
rb6 = pd.read_csv(rb_path+'6.csv')
rb7 = pd.read_csv(rb_path+'7.csv')
rb8 = pd.read_csv(rb_path+'8.csv')
rb9 = pd.read_csv(rb_path+'9.csv')
rb10 = pd.read_csv(rb_path+'10.csv')
rb11 = pd.read_csv(rb_path+'11.csv')
rb12 = pd.read_csv(rb_path+'12.csv')
rb13 = pd.read_csv(rb_path+'13.csv')
rb14 = pd.read_csv(rb_path+'14.csv')
rb15 = pd.read_csv(rb_path+'15.csv')
rb16 = pd.read_csv(rb_path+'16.csv')
rb17 = pd.read_csv(rb_path+'17.csv')

## WRs

In [5]:
wr1 = pd.read_csv(wr_path+'1.csv')
wr2 = pd.read_csv(wr_path+'2.csv')
wr3 = pd.read_csv(wr_path+'3.csv')
wr4 = pd.read_csv(wr_path+'4.csv')
wr5 = pd.read_csv(wr_path+'5.csv')
wr6 = pd.read_csv(wr_path+'6.csv')
wr7 = pd.read_csv(wr_path+'7.csv')
wr8 = pd.read_csv(wr_path+'8.csv')
wr9 = pd.read_csv(wr_path+'9.csv')
wr10 = pd.read_csv(wr_path+'10.csv')
wr11 = pd.read_csv(wr_path+'11.csv')
wr12 = pd.read_csv(wr_path+'12.csv')
wr13 = pd.read_csv(wr_path+'13.csv')
wr14 = pd.read_csv(wr_path+'14.csv')
wr15 = pd.read_csv(wr_path+'15.csv')
wr16 = pd.read_csv(wr_path+'16.csv')
wr17 = pd.read_csv(wr_path+'17.csv')

## TEs

In [6]:
te1 = pd.read_csv(te_path+'1.csv')
te2 = pd.read_csv(te_path+'2.csv')
te3 = pd.read_csv(te_path+'3.csv')
te4 = pd.read_csv(te_path+'4.csv')
te5 = pd.read_csv(te_path+'5.csv')
te6 = pd.read_csv(te_path+'6.csv')
te7 = pd.read_csv(te_path+'7.csv')
te8 = pd.read_csv(te_path+'8.csv')
te9 = pd.read_csv(te_path+'9.csv')
te10 = pd.read_csv(te_path+'10.csv')
te11 = pd.read_csv(te_path+'11.csv')
te12 = pd.read_csv(te_path+'12.csv')
te13 = pd.read_csv(te_path+'13.csv')
te14 = pd.read_csv(te_path+'14.csv')
te15 = pd.read_csv(te_path+'15.csv')
te16 = pd.read_csv(te_path+'16.csv')
te17 = pd.read_csv(te_path+'17.csv')

# Create list of weekly dataframes by position

In [8]:
qb_dfs = [qb1, qb2, qb3, qb4, qb5, qb6,
          qb7, qb8, qb9, qb10, qb11, qb12,
          qb13, qb14, qb15, qb16, qb17]

rb_dfs = [rb1, rb2, rb3, rb4, rb5, rb6,
          rb7, rb8, rb9, rb10, rb11, rb12,
          rb13, rb14, rb15, rb16, rb17]

wr_dfs = [wr1, wr2, wr3, wr4, wr5, wr6,
          wr7, wr8, wr9, wr10, wr11, wr12,
          wr13, wr14, wr15, wr16, wr17]

te_dfs = [te1, te2, te3, te4, te5, te6,
          te7, te8, te9, te10, te11, te12,
          te13, te14, te15, te16, te17]

# Add 'WK' column

In [9]:
for i in range(len(qb_dfs)):
    qb_dfs[i]['WK'] = i+1
    rb_dfs[i]['WK'] = i+1
    wr_dfs[i]['WK'] = i+1
    te_dfs[i]['WK'] = i+1

# Create one dataframe per position

In [10]:
qb = pd.concat(qb_dfs)
rb = pd.concat(rb_dfs)
wr = pd.concat(wr_dfs)
te = pd.concat(te_dfs)

# Clean up dataframes

## Drop rows with mostly NAs

In [11]:
qb = qb.dropna()
rb = rb.dropna()
wr = wr.dropna()
te = te.dropna()

## Drop unnecessary columns

In [12]:
qb = qb.drop(['G', 'FPTS/G', 'ROST'], axis=1)
rb = rb.drop(['G', 'FPTS/G', 'ROST'], axis=1)
wr = wr.drop(['G', 'FPTS/G', 'ROST'], axis=1)
te = te.drop(['G', 'FPTS/G', 'ROST'], axis=1)

## Remove teams from player names

In [13]:
for i in range(len(qb)):
    qb['Player'].iat[i] = qb['Player'].iat[i].split(' (', 1)[0]
    
for i in range(len(rb)):
    rb['Player'].iat[i] = rb['Player'].iat[i].split(' (', 1)[0]
    
for i in range(len(wr)):
    wr['Player'].iat[i] = wr['Player'].iat[i].split(' (', 1)[0]
    
for i in range(len(te)):
    te['Player'].iat[i] = te['Player'].iat[i].split(' (', 1)[0]

# WAR

WAR stands for "Wins Above Replacement." The idea is to determine how many more/fewer wins a player contributed to their team relative to a replacement-level player. To do this, we need to figure out the following info:
1. Average weekly score in my league
2. Average team score standard deviation
3. Calculate replacement-level player for each position
4. Determine each player's WAR

In [14]:
n_teams = 12
n_weeks = 17

## Average score and standard deviation

In [16]:
weekly_scores = pd.read_csv('C:\\Users\\Lenovo\\OneDrive\\Desktop\\fantasy_football\\2023\\LeagueScores.csv')
weekly_scores.head()

Week  HomeManagerID  HomeScore  AwayManagerID  AwayScore
0     1             11     113.00             10      94.82
1     1              6     135.82              5     114.66
2     1              7      50.26              2     114.66
3     1              8      83.30             12     119.40
4     1              1      96.12              9     127.18

In [17]:
home_scores = weekly_scores[['Week', 'HomeScore']].copy()
home_scores = home_scores.rename({'HomeScore': 'Score'}, axis=1)

away_scores = weekly_scores[['Week', 'AwayScore']].copy()
away_scores = away_scores.rename({'AwayScore': 'Score'}, axis=1)

all_scores = pd.concat([home_scores, away_scores])

In [18]:
all_scores.head()

Week   Score
0     1  113.00
1     1  135.82
2     1   50.26
3     1   83.30
4     1   96.12

In [56]:
weekly_avg = np.zeros(n_weeks)
weekly_std = np.zeros(n_weeks)

for i in range(n_weeks):
    weekly_avg[i] = all_scores[all_scores['Week'] == i+1]['Score'].mean()
    weekly_std[i] = all_scores[all_scores['Week'] == i+1]['Score'].std()

In [57]:
weekly_avg

array([104.86166667, 107.425     ,  95.95333333, 106.32      ,
       103.08333333,  95.64      ,  94.44833333, 118.57333333,
       102.00166667,  97.34833333, 103.84666667, 108.20666667,
       106.225     ,  99.81      , 107.73166667,  96.79166667,
        94.91666667])

In [58]:
weekly_std

array([23.88392606, 18.78185609, 16.01476667, 22.17908105, 23.36104735,
       23.75194078, 33.56761476, 24.00381535, 24.36761406, 21.30836534,
       28.73462825, 16.7278523 , 19.91837   , 16.79125422, 17.44121651,
       22.27822983, 22.2762488 ])

## Weekly replacement-level player by position

### QB

In [25]:
qb_replacements = qb[(qb['Rank'] > n_teams) & (qb['Rank'] <= n_teams*2)]

In [26]:
qb_wkly_rep_score = np.zeros(n_weeks)

for i in range(len(qb_wkly_rep_score)):
    qb_wkly_rep_score[i] = qb_replacements[qb_replacements['WK'] == i+1]['FPTS'].mean()

In [27]:
qb_wkly_rep_score

array([16.275     , 14.75833333, 14.675     , 15.13333333, 13.825     ,
       12.625     , 12.425     , 16.03333333, 12.54166667, 16.20833333,
       12.83333333, 15.41666667, 14.65833333, 12.85      , 13.85      ,
       13.05      , 12.46666667])

### RB

In [28]:
rb_replacements = rb[(rb['Rank'] > n_teams*2) & (rb['Rank'] <= n_teams*4)]

In [29]:
rb_wkly_rep_score = np.zeros(n_weeks)

for i in range(len(rb_wkly_rep_score)):
    rb_wkly_rep_score[i] = rb_replacements[rb_replacements['WK'] == i+1]['FPTS'].mean()

In [30]:
rb_wkly_rep_score

array([7.6875    , 6.61666667, 7.03333333, 7.61666667, 7.62916667,
       4.78333333, 6.65416667, 7.45416667, 4.28333333, 5.89166667,
       5.41666667, 7.94166667, 6.775     , 4.9375    , 8.05833333,
       6.1875    , 6.9125    ])

### WR

In [31]:
wr_replacements = wr[(wr['Rank'] > n_teams*2) & (wr['Rank'] <= n_teams*4)]

In [32]:
wr_wkly_rep_score = np.zeros(n_weeks)

for i in range(len(wr_wkly_rep_score)):
    wr_wkly_rep_score[i] = wr_replacements[wr_replacements['WK'] == i+1]['FPTS'].mean()

In [33]:
wr_wkly_rep_score

array([ 9.75833333, 10.0875    , 10.64166667,  8.65833333,  8.74583333,
        8.61666667,  8.6375    ,  9.35416667,  5.7125    ,  9.52083333,
        8.65833333,  9.77916667,  9.27916667,  9.09583333,  9.54583333,
        8.96666667,  6.70833333])

### TE

In [34]:
te_replacements = te[(te['Rank'] > n_teams) & (te['Rank'] <= n_teams*2)]

In [35]:
te_wkly_rep_score = np.zeros(n_weeks)

for i in range(len(te_wkly_rep_score)):
    te_wkly_rep_score[i] = te_replacements[te_replacements['WK'] == i+1]['FPTS'].mean()

In [36]:
te_wkly_rep_score

array([6.225     , 6.11666667, 6.03333333, 6.34166667, 6.04166667,
       6.93333333, 6.11666667, 6.5       , 5.25833333, 5.025     ,
       4.41666667, 5.95833333, 4.68333333, 3.78333333, 7.19166667,
       6.31666667, 8.4       ])

### FLEX

This is a bit harder to calculate since the FLEX position could be a RB, WR, or TE. I'll assume the FLEX starters are the top 12-highest scores after the top 24 RBs, top 24 WRs, and top 12 TEs are removed, and the replacement-level FLEX players are the next 12 highest scorers.

In [37]:
rb_narrow = rb[['Rank', 'Player', 'FPTS', 'WK']].copy()
wr_narrow = wr[['Rank', 'Player', 'FPTS', 'WK']].copy()
te_narrow = te[['Rank', 'Player', 'FPTS', 'WK']].copy()

In [38]:
rb_narrow['POS'] = 'RB'
wr_narrow['POS'] = 'WR'
te_narrow['POS'] = 'TE'

In [39]:
flex = pd.concat([rb_narrow, wr_narrow, te_narrow])

In [40]:
flex.head()

Rank                 Player  FPTS  WK POS
0   1.0         Saquon Barkley  30.4   1  RB
1   2.0        Jonathan Taylor  25.5   1  RB
2   3.0          D'Andre Swift  25.0   1  RB
3   4.0  Cordarrelle Patterson  21.1   1  RB
4   5.0            Kareem Hunt  21.0   1  RB

In [41]:
# Removing starting RBs, WRs, and TEs
flex = flex[((flex['POS'] == 'RB') & (flex['Rank'] > 24)) |
            ((flex['POS'] == 'WR') & (flex['Rank'] > 24)) |
            ((flex['POS'] == 'TE') & (flex['Rank'] > 12))]

In [42]:
# Sorting points each week
flex = flex.sort_values(['WK', 'FPTS'], ascending=False)

In [43]:
# Updating rank calculations
flex['Rank'] = flex.groupby(['WK']).cumcount()+1

In [44]:
# Filtering down to replacement players
flex_replacements = flex[(flex['Rank'] > n_teams) & (flex['Rank'] <=n_teams*2)]

In [45]:
flex_wkly_rep_score = np.zeros(n_weeks)

for i in range(len(flex_wkly_rep_score)):
    flex_wkly_rep_score[i] = flex_replacements[flex_replacements['WK'] == i+1]['FPTS'].mean()

In [46]:
flex_wkly_rep_score

array([ 9.125     ,  8.925     , 10.01666667,  8.99166667,  8.89166667,
        7.775     ,  8.475     ,  9.20833333,  5.98333333,  8.625     ,
        8.04166667,  9.61666667,  8.7       ,  7.90833333,  9.91666667,
        8.54166667,  7.99166667])

## Individual Player WAR

In [47]:
qb.head()

Rank              Player   CMP   ATT   PCT    YDS  Y/A   TD  INT  SACKS  \
0   1.0  Patrick Mahomes II  30.0  39.0  76.9  360.0  9.2  5.0  0.0    0.0   
1   2.0          Josh Allen  26.0  31.0  83.9  297.0  9.6  3.0  2.0    2.0   
2   3.0        Carson Wentz  27.0  41.0  65.9  313.0  7.6  4.0  2.0    1.0   
3   4.0         Jalen Hurts  18.0  32.0  56.3  243.0  7.6  0.0  0.0    1.0   
4   5.0      Justin Herbert  26.0  34.0  76.5  279.0  8.2  3.0  0.0    0.0   

   ATT.1  YDS.1  TD.1   FL  FPTS  WK  
0    3.0    5.0   0.0  0.0  34.9   1  
1   10.0   56.0   1.0  0.0  33.5   1  
2    6.0   12.0   0.0  0.0  29.7   1  
3   17.0   90.0   1.0  0.0  24.7   1  
4    4.0    1.0   0.0  0.0  23.3   1

In [48]:
qb_players = qb['Player'].unique()

In [53]:
qb_players[:5]

array(['Patrick Mahomes II', 'Josh Allen', 'Carson Wentz', 'Jalen Hurts',
       'Justin Herbert'], dtype=object)

In [51]:
qb_wkly_rep_score

array([16.275     , 14.75833333, 14.675     , 15.13333333, 13.825     ,
       12.625     , 12.425     , 16.03333333, 12.54166667, 16.20833333,
       12.83333333, 15.41666667, 14.65833333, 12.85      , 13.85      ,
       13.05      , 12.46666667])

In [79]:
mahomes_contribution = np.zeros(n_weeks)
mahomes_exp_team_score = np.zeros(n_weeks)
mahomes_win_probs = np.zeros(n_weeks)

for i in range(n_weeks):
    mahomes_contribution[i] = qb[(qb['Player'] == 'Patrick Mahomes II') & (qb['WK'] == i+1)]['FPTS'] - qb_wkly_rep_score[i]
    mahomes_exp_team_score[i] = weekly_avg[i] + mahomes_contribution[i]

mahomes_z_score = (mahomes_exp_team_score - weekly_avg)/weekly_std

for i in range(n_weeks):
    mahomes_win_prob[i] = st.norm.cdf(mahomes_z_score[i])

In [80]:
mahomes_win_prob

array([0.78224957, 0.55382279, 0.58467388, 0.66195739, 0.76232304,
       0.64723413, 0.67760422, 0.25208296, 0.8227122 , 0.77210429,
       0.69512062, 0.59410824, 0.60184938, 0.72326565, 0.860101  ,
       0.68528662, 0.72824806])

In [82]:
def get_player_exp_team_scores(player, position_df, weekly_pos_scores):
     
    
    player_contribution = np.zeros(n_weeks)
    player_exp_team_score = np.zeros(n_weeks)
    
    for i in range(n_weeks):
        player_contribution[i] = position_df[(position_df['Player'] == player) & (position_df['WK'] == i+1)]['FPTS'] - weekly_pos_scores[i]
        player_exp_team_score[i] = weekly_avg[i] + player_contribution[i]
        
    return player_exp_team_score

In [88]:
def get_player_win_prob(player_exp_team_score):
    
    player_win_prob = np.zeros(n_weeks)
    player_z_score = (player_exp_team_score - weekly_avg)/weekly_std
    
    for i in range(n_weeks):
        player_win_prob[i] = st.norm.cdf(mahomes_z_score[i])
        
    return player_win_prob

In [97]:
def calculate_player_war(player, position_df, weekly_pos_scores):

    
    player_exp_team_scores = get_player_exp_team_scores(player, position_df, weekly_pos_scores)
    
    player_win_probs = get_player_win_prob(player_exp_team_scores)
    
    return player_win_probs

In [98]:
calculate_player_war('Patrick Mahomes II', qb, qb_wkly_rep_score)

array([0.78224957, 0.55382279, 0.58467388, 0.66195739, 0.76232304,
       0.64723413, 0.67760422, 0.25208296, 0.8227122 , 0.77210429,
       0.69512062, 0.59410824, 0.60184938, 0.72326565, 0.860101  ,
       0.68528662, 0.72824806])