# Data Source

I'm using weekly fantasy football data downloaded from [FantasyPros](https://www.fantasypros.com/). Specifically, I downloaded weekly data by position with the settings of Half PPR and Consensus Roster %. You can access an example week [here](https://www.fantasypros.com/nfl/stats/qb.php?week=1&scoring=HALF&range=week).

# Load in libraries

In [1]:
import pandas as pd
import numpy as np
import scipy.stats as st

# Basic League Info

In [2]:
n_teams = 12
n_weeks = 17

# Set file path for each position

In [3]:
qb_path = 'C:\\Users\\Lenovo\\OneDrive\\Desktop\\fantasy_football\\2023\\QB_'
rb_path = 'C:\\Users\\Lenovo\\OneDrive\\Desktop\\fantasy_football\\2023\\RB_'
wr_path = 'C:\\Users\\Lenovo\\OneDrive\\Desktop\\fantasy_football\\2023\\WR_'
te_path = 'C:\\Users\\Lenovo\\OneDrive\\Desktop\\fantasy_football\\2023\\TE_'

# Load in weekly data

## QBs

In [4]:
qb1 = pd.read_csv(qb_path+'1.csv')
qb2 = pd.read_csv(qb_path+'2.csv')
qb3 = pd.read_csv(qb_path+'3.csv')
qb4 = pd.read_csv(qb_path+'4.csv')
qb5 = pd.read_csv(qb_path+'5.csv')
qb6 = pd.read_csv(qb_path+'6.csv')
qb7 = pd.read_csv(qb_path+'7.csv')
qb8 = pd.read_csv(qb_path+'8.csv')
qb9 = pd.read_csv(qb_path+'9.csv')
qb10 = pd.read_csv(qb_path+'10.csv')
qb11 = pd.read_csv(qb_path+'11.csv')
qb12 = pd.read_csv(qb_path+'12.csv')
qb13 = pd.read_csv(qb_path+'13.csv')
qb14 = pd.read_csv(qb_path+'14.csv')
qb15 = pd.read_csv(qb_path+'15.csv')
qb16 = pd.read_csv(qb_path+'16.csv')
qb17 = pd.read_csv(qb_path+'17.csv')

## RBs

In [5]:
rb1 = pd.read_csv(rb_path+'1.csv')
rb2 = pd.read_csv(rb_path+'2.csv')
rb3 = pd.read_csv(rb_path+'3.csv')
rb4 = pd.read_csv(rb_path+'4.csv')
rb5 = pd.read_csv(rb_path+'5.csv')
rb6 = pd.read_csv(rb_path+'6.csv')
rb7 = pd.read_csv(rb_path+'7.csv')
rb8 = pd.read_csv(rb_path+'8.csv')
rb9 = pd.read_csv(rb_path+'9.csv')
rb10 = pd.read_csv(rb_path+'10.csv')
rb11 = pd.read_csv(rb_path+'11.csv')
rb12 = pd.read_csv(rb_path+'12.csv')
rb13 = pd.read_csv(rb_path+'13.csv')
rb14 = pd.read_csv(rb_path+'14.csv')
rb15 = pd.read_csv(rb_path+'15.csv')
rb16 = pd.read_csv(rb_path+'16.csv')
rb17 = pd.read_csv(rb_path+'17.csv')

## WRs

In [6]:
wr1 = pd.read_csv(wr_path+'1.csv')
wr2 = pd.read_csv(wr_path+'2.csv')
wr3 = pd.read_csv(wr_path+'3.csv')
wr4 = pd.read_csv(wr_path+'4.csv')
wr5 = pd.read_csv(wr_path+'5.csv')
wr6 = pd.read_csv(wr_path+'6.csv')
wr7 = pd.read_csv(wr_path+'7.csv')
wr8 = pd.read_csv(wr_path+'8.csv')
wr9 = pd.read_csv(wr_path+'9.csv')
wr10 = pd.read_csv(wr_path+'10.csv')
wr11 = pd.read_csv(wr_path+'11.csv')
wr12 = pd.read_csv(wr_path+'12.csv')
wr13 = pd.read_csv(wr_path+'13.csv')
wr14 = pd.read_csv(wr_path+'14.csv')
wr15 = pd.read_csv(wr_path+'15.csv')
wr16 = pd.read_csv(wr_path+'16.csv')
wr17 = pd.read_csv(wr_path+'17.csv')

## TEs

In [7]:
te1 = pd.read_csv(te_path+'1.csv')
te2 = pd.read_csv(te_path+'2.csv')
te3 = pd.read_csv(te_path+'3.csv')
te4 = pd.read_csv(te_path+'4.csv')
te5 = pd.read_csv(te_path+'5.csv')
te6 = pd.read_csv(te_path+'6.csv')
te7 = pd.read_csv(te_path+'7.csv')
te8 = pd.read_csv(te_path+'8.csv')
te9 = pd.read_csv(te_path+'9.csv')
te10 = pd.read_csv(te_path+'10.csv')
te11 = pd.read_csv(te_path+'11.csv')
te12 = pd.read_csv(te_path+'12.csv')
te13 = pd.read_csv(te_path+'13.csv')
te14 = pd.read_csv(te_path+'14.csv')
te15 = pd.read_csv(te_path+'15.csv')
te16 = pd.read_csv(te_path+'16.csv')
te17 = pd.read_csv(te_path+'17.csv')

# Create list of weekly dataframes by position

In [8]:
qb_dfs = [qb1, qb2, qb3, qb4, qb5, qb6,
          qb7, qb8, qb9, qb10, qb11, qb12,
          qb13, qb14, qb15, qb16, qb17]

rb_dfs = [rb1, rb2, rb3, rb4, rb5, rb6,
          rb7, rb8, rb9, rb10, rb11, rb12,
          rb13, rb14, rb15, rb16, rb17]

wr_dfs = [wr1, wr2, wr3, wr4, wr5, wr6,
          wr7, wr8, wr9, wr10, wr11, wr12,
          wr13, wr14, wr15, wr16, wr17]

te_dfs = [te1, te2, te3, te4, te5, te6,
          te7, te8, te9, te10, te11, te12,
          te13, te14, te15, te16, te17]

# Add 'WK' column

In [9]:
for i in range(len(qb_dfs)):
    qb_dfs[i]['WK'] = i+1
    rb_dfs[i]['WK'] = i+1
    wr_dfs[i]['WK'] = i+1
    te_dfs[i]['WK'] = i+1

# Create one dataframe per position

In [10]:
qb = pd.concat(qb_dfs)
rb = pd.concat(rb_dfs)
wr = pd.concat(wr_dfs)
te = pd.concat(te_dfs)

# Clean up dataframes

## Drop rows with mostly NAs

In [11]:
qb = qb.dropna()
rb = rb.dropna()
wr = wr.dropna()
te = te.dropna()

## Drop unnecessary columns

In [12]:
qb = qb.drop(['G', 'FPTS/G', 'ROST'], axis=1)
rb = rb.drop(['G', 'FPTS/G', 'ROST'], axis=1)
wr = wr.drop(['G', 'FPTS/G', 'ROST'], axis=1)
te = te.drop(['G', 'FPTS/G', 'ROST'], axis=1)

## Remove teams from player names

In [13]:
for i in range(len(qb)):
    qb['Player'].iat[i] = qb['Player'].iat[i].split(' (', 1)[0]
    
for i in range(len(rb)):
    rb['Player'].iat[i] = rb['Player'].iat[i].split(' (', 1)[0]
    
for i in range(len(wr)):
    wr['Player'].iat[i] = wr['Player'].iat[i].split(' (', 1)[0]
    
for i in range(len(te)):
    te['Player'].iat[i] = te['Player'].iat[i].split(' (', 1)[0]

## Add in 0 pts for players in weeks where they don't appear

In [14]:
qb_players = qb['Player'].unique()
rb_players = rb['Player'].unique()
wr_players = wr['Player'].unique()
te_players = te['Player'].unique()

In [15]:
for i in range(n_weeks):
    
    # Insert rows for QBs missing weekly data
    for qb_name in qb_players:
        if i+1 not in pd.Series(qb[qb['Player'] == qb_name]['WK']).unique():
            qb.loc[len(qb.index)] = [999, qb_name, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, i+1]
            
    # Insert rows for RBs missing weekly data
    for rb_name in rb_players:
        if i+1 not in pd.Series(rb[rb['Player'] == rb_name]['WK']).unique():
            rb.loc[len(rb.index)] = [999, rb_name, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, i+1]

    # Insert rows for WRs missing weekly data
    for wr_name in wr_players:
        if i+1 not in pd.Series(wr[wr['Player'] == wr_name]['WK']).unique():
            wr.loc[len(wr.index)] = [999, rb_name, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, i+1]
    
    # Insert rows for TEs missing weekly data
    for te_name in te_players:
        if i+1 not in pd.Series(te[te['Player'] == te_name]['WK']).unique():
            te.loc[len(te.index)] = [999, te_name, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, i+1]

In [16]:
# Sort by week and then rank
qb = qb.sort_values(['WK', 'Rank', 'Player'])
rb = rb.sort_values(['WK', 'Rank', 'Player'])
wr = wr.sort_values(['WK', 'Rank', 'Player'])
te = te.sort_values(['WK', 'Rank', 'Player'])


# Resetting indexes
qb.reset_index(drop = True, inplace = True)
rb.reset_index(drop = True, inplace = True)
wr.reset_index(drop = True, inplace = True)
te.reset_index(drop = True, inplace = True)

In [81]:
rb[rb['Player'] == 'Phillip Lindsay']

Rank           Player   ATT   YDS  Y/A    LG  20+   TD  REC  TGT  \
265   999.0  Phillip Lindsay   0.0   0.0  0.0   0.0  0.0  0.0  0.0  0.0   
535   999.0  Phillip Lindsay   0.0   0.0  0.0   0.0  0.0  0.0  0.0  0.0   
803   999.0  Phillip Lindsay   0.0   0.0  0.0   0.0  0.0  0.0  0.0  0.0   
1074  999.0  Phillip Lindsay   0.0   0.0  0.0   0.0  0.0  0.0  0.0  0.0   
1117   38.0  Phillip Lindsay  11.0  40.0  3.6  15.0  0.0  0.0  3.0  4.0   
1387   38.0  Phillip Lindsay   3.0   7.0  2.3   3.0  0.0  0.0  3.0  3.0   
1885  999.0  Phillip Lindsay   0.0   0.0  0.0   0.0  0.0  0.0  0.0  0.0   
2154  999.0  Phillip Lindsay   0.0   0.0  0.0   0.0  0.0  0.0  0.0  0.0   
2231   71.0  Phillip Lindsay   1.0   2.0  2.0   2.0  0.0  0.0  0.0  1.0   
2695  999.0  Phillip Lindsay   0.0   0.0  0.0   0.0  0.0  0.0  0.0  0.0   
2964  999.0  Phillip Lindsay   0.0   0.0  0.0   0.0  0.0  0.0  0.0  0.0   
3235  999.0  Phillip Lindsay   0.0   0.0  0.0   0.0  0.0  0.0  0.0  0.0   
3503  999.0  Phillip Lindsay   0.0   0.0  0.0   0.0  0.0  0.0  0.0  0.0   
3774  999.0  Phillip Lindsay   0.0   0.0  0.0   0.0  0.0  0.0  0.0  0.0   
4046  999.0  Phillip Lindsay   0.0   0.0  0.0   0.0  0.0  0.0  0.0  0.0   
4316  999.0  Phillip Lindsay   0.0   0.0  0.0   0.0  0.0  0.0  0.0  0.0   
4586  999.0  Phillip Lindsay   0.0   0.0  0.0   0.0  0.0  0.0  0.0  0.0   

      YDS.1  Y/R  TD.1   FL  FPTS  WK  
265     0.0  0.0   0.0  0.0   0.0   1  
535     0.0  0.0   0.0  0.0   0.0   2  
803     0.0  0.0   0.0  0.0   0.0   3  
1074    0.0  0.0   0.0  0.0   0.0   4  
1117   14.0  4.7   0.0  0.0   6.9   5  
1387    5.0  1.7   0.0  0.0   4.7   6  
1885    0.0  0.0   0.0  0.0   0.0   7  
2154    0.0  0.0   0.0  0.0   0.0   8  
2231    0.0  0.0   0.0  0.0   0.2   9  
2695    0.0  0.0   0.0  0.0   0.0  10  
2964    0.0  0.0   0.0  0.0   0.0  11  
3235    0.0  0.0   0.0  0.0   0.0  12  
3503    0.0  0.0   0.0  0.0   0.0  13  
3774    0.0  0.0   0.0  0.0   0.0  14  
4046    0.0  0.0   0.0  0.0   0.0  15  
4316    0.0  0.0   0.0  0.0   0.0  16  
4586    0.0  0.0   0.0  0.0   0.0  17

In [82]:
calculate_player_exp_wins('Phillip Lindsay', 'RB')

5.348579991211994

# WAR

WAR stands for "Wins Above Replacement." The idea is to determine how many more/fewer wins a player contributed to their team relative to a replacement-level player. To do this, we need to figure out the following info:
1. Average weekly score in my league
2. Average team score standard deviation
3. Calculate replacement-level player for each position
4. Determine each player's WAR

## Average score and standard deviation

In [17]:
weekly_scores = pd.read_csv('C:\\Users\\Lenovo\\OneDrive\\Desktop\\fantasy_football\\2023\\LeagueScores.csv')
weekly_scores.head()

Week  HomeManagerID  HomeScore  AwayManagerID  AwayScore
0     1             11     113.00             10      94.82
1     1              6     135.82              5     114.66
2     1              7      50.26              2     114.66
3     1              8      83.30             12     119.40
4     1              1      96.12              9     127.18

In [18]:
home_scores = weekly_scores[['Week', 'HomeScore']].copy()
home_scores = home_scores.rename({'HomeScore': 'Score'}, axis=1)

away_scores = weekly_scores[['Week', 'AwayScore']].copy()
away_scores = away_scores.rename({'AwayScore': 'Score'}, axis=1)

all_scores = pd.concat([home_scores, away_scores])

In [19]:
all_scores.head()

Week   Score
0     1  113.00
1     1  135.82
2     1   50.26
3     1   83.30
4     1   96.12

In [20]:
weekly_avg = np.zeros(n_weeks)
weekly_std = np.zeros(n_weeks)

for i in range(n_weeks):
    weekly_avg[i] = all_scores[all_scores['Week'] == i+1]['Score'].mean()
    weekly_std[i] = all_scores[all_scores['Week'] == i+1]['Score'].std()

In [21]:
weekly_avg

array([104.86166667, 107.425     ,  95.95333333, 106.32      ,
       103.08333333,  95.64      ,  94.44833333, 118.57333333,
       102.00166667,  97.34833333, 103.84666667, 108.20666667,
       106.225     ,  99.81      , 107.73166667,  96.79166667,
        94.91666667])

In [22]:
weekly_std

array([23.88392606, 18.78185609, 16.01476667, 22.17908105, 23.36104735,
       23.75194078, 33.56761476, 24.00381535, 24.36761406, 21.30836534,
       28.73462825, 16.7278523 , 19.91837   , 16.79125422, 17.44121651,
       22.27822983, 22.2762488 ])

## Weekly replacement-level player by position

### QB

In [23]:
qb_replacements = qb[(qb['Rank'] > n_teams) & (qb['Rank'] <= n_teams*2)]
qb_starters = qb[qb['Rank'] <= n_teams]

In [24]:
qb_rep_score = np.zeros(n_weeks)

for i in range(n_weeks):
    qb_rep_score[i] = qb_replacements[qb_replacements['WK'] == i+1]['FPTS'].mean()

In [25]:
qb_rep_score

array([16.275     , 14.75833333, 14.675     , 15.13333333, 13.825     ,
       12.625     , 12.425     , 16.03333333, 12.54166667, 16.20833333,
       12.83333333, 15.41666667, 14.65833333, 12.85      , 13.85      ,
       13.05      , 12.46666667])

In [26]:
qb_exp_score = np.zeros(n_weeks)

for i in range(n_weeks):
    qb_exp_score[i] = qb_starters[qb_starters['WK'] == i+1]['FPTS'].mean()

In [27]:
qb_exp_score

array([24.16666667, 28.225     , 23.05      , 24.41666667, 22.8       ,
       22.26666667, 22.7       , 24.05833333, 23.21666667, 23.525     ,
       23.76666667, 24.76666667, 21.60833333, 23.90833333, 26.43333333,
       22.9       , 24.04166667])

### RB

In [28]:
rb_replacements = rb[(rb['Rank'] > n_teams*2) & (rb['Rank'] <= n_teams*4)]
rb_starters = rb[rb['Rank'] <= n_teams*2]

In [29]:
rb_rep_score = np.zeros(n_weeks)

for i in range(n_weeks):
    rb_rep_score[i] = rb_replacements[rb_replacements['WK'] == i+1]['FPTS'].mean()

In [30]:
rb_rep_score

array([7.6875    , 6.61666667, 7.03333333, 7.61666667, 7.62916667,
       4.78333333, 6.65416667, 7.45416667, 4.28333333, 5.89166667,
       5.41666667, 7.94166667, 6.775     , 4.9375    , 8.05833333,
       6.1875    , 6.9125    ])

In [31]:
rb_exp_score = np.zeros(n_weeks)

for i in range(n_weeks):
    rb_exp_score[i] = rb_starters[rb_starters['WK'] == i+1]['FPTS'].mean()

In [32]:
rb_exp_score

array([17.04583333, 13.67916667, 16.01666667, 18.62083333, 19.92083333,
       14.77916667, 18.14583333, 20.01666667, 16.17083333, 15.7875    ,
       16.14583333, 17.575     , 15.25833333, 15.9875    , 17.7125    ,
       16.13333333, 16.25      ])

### WR

In [33]:
wr_replacements = wr[(wr['Rank'] > n_teams*2) & (wr['Rank'] <= n_teams*4)]
wr_starters = wr[wr['Rank'] <= n_teams*2]

In [34]:
wr_rep_score = np.zeros(n_weeks)

for i in range(n_weeks):
    wr_rep_score[i] = wr_replacements[wr_replacements['WK'] == i+1]['FPTS'].mean()

In [35]:
wr_rep_score

array([ 9.75833333, 10.0875    , 10.64166667,  8.65833333,  8.74583333,
        8.61666667,  8.6375    ,  9.35416667,  5.7125    ,  9.52083333,
        8.65833333,  9.77916667,  9.27916667,  9.09583333,  9.54583333,
        8.96666667,  6.70833333])

In [36]:
wr_exp_score = np.zeros(n_weeks)

for i in range(n_weeks):
    wr_exp_score[i] = wr_starters[wr_starters['WK'] == i+1]['FPTS'].mean()

In [37]:
wr_exp_score

array([18.5375    , 21.12916667, 17.35      , 16.83333333, 17.1375    ,
       16.86666667, 16.31666667, 18.20416667, 15.4       , 18.5375    ,
       16.12916667, 17.37916667, 18.77916667, 17.        , 17.39166667,
       17.39583333, 16.77916667])

### TE

In [38]:
te_replacements = te[(te['Rank'] > n_teams) & (te['Rank'] <= n_teams*2)]
te_starters = te[te['Rank'] <= n_teams]

In [39]:
te_rep_score = np.zeros(n_weeks)

for i in range(n_weeks):
    te_rep_score[i] = te_replacements[te_replacements['WK'] == i+1]['FPTS'].mean()

In [40]:
te_rep_score

array([6.225     , 6.11666667, 6.03333333, 6.34166667, 6.04166667,
       6.93333333, 6.11666667, 6.5       , 5.25833333, 5.025     ,
       4.41666667, 5.95833333, 4.68333333, 3.78333333, 7.19166667,
       6.31666667, 8.4       ])

In [41]:
te_exp_score = np.zeros(n_weeks)

for i in range(n_weeks):
    te_exp_score[i] = te_starters[te_starters['WK'] == i+1]['FPTS'].mean()

In [42]:
te_exp_score

array([12.25      , 11.89166667, 13.04166667, 15.33333333, 14.61666667,
       13.725     , 11.05833333, 12.65      , 12.34166667, 11.59166667,
       12.63333333, 12.43333333, 10.05833333, 12.19166667, 14.425     ,
       16.48333333, 13.7       ])

### FLEX

This is a bit harder to calculate since the FLEX position could be a RB, WR, or TE. I'll assume the FLEX starters are the top 12-highest scores after the top 24 RBs, top 24 WRs, and top 12 TEs are removed, and the replacement-level FLEX players are the next 12 highest scorers.

In [43]:
rb_narrow = rb[['Rank', 'Player', 'FPTS', 'WK']].copy()
wr_narrow = wr[['Rank', 'Player', 'FPTS', 'WK']].copy()
te_narrow = te[['Rank', 'Player', 'FPTS', 'WK']].copy()

In [44]:
rb_narrow['POS'] = 'RB'
wr_narrow['POS'] = 'WR'
te_narrow['POS'] = 'TE'

In [45]:
flex = pd.concat([rb_narrow, wr_narrow, te_narrow])

In [46]:
flex.head()

Rank                 Player  FPTS  WK POS
0   1.0         Saquon Barkley  30.4   1  RB
1   2.0        Jonathan Taylor  25.5   1  RB
2   3.0          D'Andre Swift  25.0   1  RB
3   4.0  Cordarrelle Patterson  21.1   1  RB
4   5.0            Kareem Hunt  21.0   1  RB

In [47]:
# Removing starting RBs, WRs, and TEs
flex = flex[((flex['POS'] == 'RB') & (flex['Rank'] > 24)) |
            ((flex['POS'] == 'WR') & (flex['Rank'] > 24)) |
            ((flex['POS'] == 'TE') & (flex['Rank'] > 12))]

In [48]:
# Sorting points each week
flex = flex.sort_values(['WK', 'FPTS'], ascending=False)

In [49]:
# Updating rank calculations
flex['Rank'] = flex.groupby(['WK']).cumcount()+1

In [50]:
# Filtering down to replacement players
flex_replacements = flex[(flex['Rank'] > n_teams) & (flex['Rank'] <=n_teams*2)]
flex_starters = flex[flex['Rank'] <= n_teams]

In [51]:
flex_rep_score = np.zeros(n_weeks)

for i in range(n_weeks):
    flex_rep_score[i] = flex_replacements[flex_replacements['WK'] == i+1]['FPTS'].mean()

In [52]:
flex_rep_score

array([ 9.125     ,  8.925     , 10.01666667,  8.99166667,  8.89166667,
        7.775     ,  8.475     ,  9.20833333,  5.98333333,  8.625     ,
        8.04166667,  9.61666667,  8.7       ,  7.90833333,  9.91666667,
        8.54166667,  7.99166667])

In [53]:
flex_exp_score = np.zeros(n_weeks)

for i in range(n_weeks):
    flex_exp_score[i] = flex_starters[flex_starters['WK'] == i+1]['FPTS'].mean()

In [54]:
flex_exp_score

array([10.93333333, 11.4       , 11.95      , 10.11666667, 10.21666667,
       10.23333333, 10.375     , 10.23333333,  7.375     , 10.975     ,
        9.80833333, 11.275     , 10.45833333, 10.59166667, 11.21666667,
       10.46666667,  8.975     ])

## Individual Player WAR

### Defining functions

In [55]:
def collect_dataframes(player, position):
    """
    Return correct positional dataframes. This simplifies future coding by limiting the
    number of parameters that need to be passed in to the main function.
    """
    
    if position == 'QB':
        return (qb, qb_exp_score, qb_rep_score)
    
    elif position == 'RB':
        return (rb, rb_exp_score, rb_rep_score)
    
    elif position == 'WR':
        return (wr, wr_exp_score, wr_rep_score)
    
    else:
        return (te, te_exp_score, te_rep_score)

In [56]:
def get_player_exp_team_scores(player, position_df, exp_df, rep_df):
    """  
    Return the expected team scores by week for a player
    """
    
    # Create needed arrays
    player_scores = np.zeros(n_weeks)
    player_exp_team_scores = np.zeros(n_weeks)
    
    # Get player's scores for each week
    for i in range(n_weeks):
        player_scores[i] = position_df[(position_df['Player'] == player) & (position_df['WK'] == i+1)]['FPTS']
        
        # Replace 0s with replacement-level scores
        if player_scores[i] == 0:
            player_scores[i] = rep_df[i]
        
        player_exp_team_scores[i] = weekly_avg[i] - exp_df[i] + player_scores[i]
        
    return player_exp_team_scores

In [57]:
def get_player_win_prob(player_exp_team_scores):
    """
    Return the expected win probability for a team given that team's expected score
    """
    
    player_win_prob = np.zeros(n_weeks)
    player_z_score = (player_exp_team_scores - weekly_avg)/weekly_std
    
    for i in range(n_weeks):
        player_win_prob[i] = st.norm.cdf(player_z_score[i])
        
    return player_win_prob

In [58]:
def calculate_player_exp_wins(player, position):
    """
    Calculate the expected wins from a particular player assuming they start every week
    in which they are available.
    """
    
    # Get correct dataframes
    pos_df, exp_df, rep_df = collect_dataframes(player, position)
    
    # Get expected weekly scores with that player
    player_exp_team_scores = get_player_exp_team_scores(player, pos_df, exp_df, rep_df)
    
    # Get weekly win probability
    player_win_probs = get_player_win_prob(player_exp_team_scores)
    
    return sum(player_win_probs)

### Calculating replacement player exp. wins

In [59]:
rep_qb_exp_team_scores = weekly_avg - qb_exp_score + qb_rep_score
rep_rb_exp_team_scores = weekly_avg - rb_exp_score + rb_rep_score
rep_wr_exp_team_scores = weekly_avg - wr_exp_score + wr_rep_score
rep_te_exp_team_scores = weekly_avg - te_exp_score + te_rep_score
rep_flex_exp_team_scores = weekly_avg - flex_exp_score + flex_rep_score

In [60]:
rep_qb_win_prob = np.zeros(n_weeks)
rep_rb_win_prob = np.zeros(n_weeks)
rep_wr_win_prob = np.zeros(n_weeks)
rep_te_win_prob = np.zeros(n_weeks)
rep_flex_win_prob = np.zeros(n_weeks)

rep_qb_z_score = (rep_qb_exp_team_scores - weekly_avg)/weekly_std
rep_rb_z_score = (rep_rb_exp_team_scores - weekly_avg)/weekly_std
rep_wr_z_score = (rep_wr_exp_team_scores - weekly_avg)/weekly_std
rep_te_z_score = (rep_te_exp_team_scores - weekly_avg)/weekly_std
rep_flex_z_score = (rep_flex_exp_team_scores - weekly_avg)/weekly_std

for i in range(n_weeks):
    rep_qb_win_prob[i] = st.norm.cdf(rep_qb_z_score[i])
    rep_rb_win_prob[i] = st.norm.cdf(rep_rb_z_score[i])
    rep_wr_win_prob[i] = st.norm.cdf(rep_wr_z_score[i])
    rep_te_win_prob[i] = st.norm.cdf(rep_te_z_score[i])
    rep_flex_win_prob[i] = st.norm.cdf(rep_flex_z_score[i])

In [61]:
qb_rep_exp_wins = sum(rep_qb_win_prob)
rb_rep_exp_wins = sum(rep_rb_win_prob)
wr_rep_exp_wins = sum(rep_wr_win_prob)
te_rep_exp_wins = sum(rep_te_win_prob)
flex_rep_exp_wins = sum(rep_flex_win_prob)

print(f'Expected wins from replacement QB: {qb_rep_exp_wins:.3}')
print(f'Expected wins from replacement RB: {rb_rep_exp_wins:.3}')
print(f'Expected wins from replacement WR: {wr_rep_exp_wins:.3}')
print(f'Expected wins from replacement TE: {te_rep_exp_wins:.3}')
print(f'Expected wins from replacement FLEX: {flex_rep_exp_wins:.3}')

Expected wins from replacement QB: 5.51
Expected wins from replacement RB: 5.42
Expected wins from replacement WR: 5.86
Expected wins from replacement TE: 6.31
Expected wins from replacement FLEX: 7.93


### Getting individual WARs

Problem to solve now: Some players weren't on consensus roster for all 17 weeks, and the expected team score functions fail in those cases. I need to build accomodations for that situation.

In [73]:
flex_players = flex['Player'].unique()

qb_war = np.zeros(len(qb_players))
rb_war = np.zeros(len(rb_players))
wr_war = np.zeros(len(wr_players))
te_war = np.zeros(len(te_players))
flex_war = np.zeros(len(flex_players))

In [75]:
# Get QB WAR
for i in range(len(qb_war)):
    qb_war[i] = calculate_player_exp_wins(qb_players[i], 'QB') - qb_rep_exp_wins
   

In [77]:
 
# Calculate RB WAR
for i in range(len(rb_war)):
    rb_war[i] = calculate_player_exp_wins(rb_players[i], 'RB') - rb_rep_exp_wins
   

ValueError: setting an array element with a sequence.

In [76]:
 
# Calculate WR WAR
for i in range(len(wr_war)):
    wr_war[i] = calculate_player_exp_wins(wr_players[i], 'WR') - wr_rep_exp_wins
    
# Calculate TE WAR
for i in range(len(te_war)):
    te_war[i] = calculate_player_exp_wins(te_players[i], 'TE') - te_rep_exp_wins

# Calculate FLEX WAR
for i in range(len(flex_war)):
    flex_war[i] = calculate_player_exp_wins(flex_players[i], 'FLEX') - flex_rep_exp_wins

ValueError: setting an array element with a sequence.

In [69]:
qb_players[-2]

'Davis Cheek'

In [72]:
qb_war_df = pd.DataFrame({'Player': qb_players, 'WAR': qb_war})
qb_war_df = qb_war_df[qb_war_df['WAR'] != 0]
qb_war_df

Player       WAR
0    Patrick Mahomes II  3.270787
1            Josh Allen  3.114525
2          Carson Wentz  0.211355
3           Jalen Hurts  3.348685
4        Justin Herbert  0.898214
..                  ...       ...
131   Teddy Bridgewater  0.032463
132         Jacob Eason -0.152567
133       Bryce Perkins -0.796758
134        Chase Daniel -0.150132
136          Nick Foles -0.276147

[77 rows x 2 columns]