# Data Source

I'm using weekly fantasy football data downloaded from [FantasyPros](https://www.fantasypros.com/). Specifically, I downloaded weekly data by position with the settings of Half PPR and Consensus Roster %. You can access an example week [here](https://www.fantasypros.com/nfl/stats/qb.php?week=1&scoring=HALF&range=week).

# Load in libraries

In [1]:
import pandas as pd
import numpy as np
import scipy.stats as st

# Basic League Info

In [2]:
n_teams = 12
n_weeks = 17

# Set file path for each position

In [3]:
qb_path = 'C:\\Users\\Lenovo\\OneDrive\\Desktop\\fantasy_football\\2023\\QB_'
rb_path = 'C:\\Users\\Lenovo\\OneDrive\\Desktop\\fantasy_football\\2023\\RB_'
wr_path = 'C:\\Users\\Lenovo\\OneDrive\\Desktop\\fantasy_football\\2023\\WR_'
te_path = 'C:\\Users\\Lenovo\\OneDrive\\Desktop\\fantasy_football\\2023\\TE_'

# Load in weekly data

## QBs

In [4]:
qb1 = pd.read_csv(qb_path+'1.csv')
qb2 = pd.read_csv(qb_path+'2.csv')
qb3 = pd.read_csv(qb_path+'3.csv')
qb4 = pd.read_csv(qb_path+'4.csv')
qb5 = pd.read_csv(qb_path+'5.csv')
qb6 = pd.read_csv(qb_path+'6.csv')
qb7 = pd.read_csv(qb_path+'7.csv')
qb8 = pd.read_csv(qb_path+'8.csv')
qb9 = pd.read_csv(qb_path+'9.csv')
qb10 = pd.read_csv(qb_path+'10.csv')
qb11 = pd.read_csv(qb_path+'11.csv')
qb12 = pd.read_csv(qb_path+'12.csv')
qb13 = pd.read_csv(qb_path+'13.csv')
qb14 = pd.read_csv(qb_path+'14.csv')
qb15 = pd.read_csv(qb_path+'15.csv')
qb16 = pd.read_csv(qb_path+'16.csv')
qb17 = pd.read_csv(qb_path+'17.csv')

## RBs

In [5]:
rb1 = pd.read_csv(rb_path+'1.csv')
rb2 = pd.read_csv(rb_path+'2.csv')
rb3 = pd.read_csv(rb_path+'3.csv')
rb4 = pd.read_csv(rb_path+'4.csv')
rb5 = pd.read_csv(rb_path+'5.csv')
rb6 = pd.read_csv(rb_path+'6.csv')
rb7 = pd.read_csv(rb_path+'7.csv')
rb8 = pd.read_csv(rb_path+'8.csv')
rb9 = pd.read_csv(rb_path+'9.csv')
rb10 = pd.read_csv(rb_path+'10.csv')
rb11 = pd.read_csv(rb_path+'11.csv')
rb12 = pd.read_csv(rb_path+'12.csv')
rb13 = pd.read_csv(rb_path+'13.csv')
rb14 = pd.read_csv(rb_path+'14.csv')
rb15 = pd.read_csv(rb_path+'15.csv')
rb16 = pd.read_csv(rb_path+'16.csv')
rb17 = pd.read_csv(rb_path+'17.csv')

## WRs

In [6]:
wr1 = pd.read_csv(wr_path+'1.csv')
wr2 = pd.read_csv(wr_path+'2.csv')
wr3 = pd.read_csv(wr_path+'3.csv')
wr4 = pd.read_csv(wr_path+'4.csv')
wr5 = pd.read_csv(wr_path+'5.csv')
wr6 = pd.read_csv(wr_path+'6.csv')
wr7 = pd.read_csv(wr_path+'7.csv')
wr8 = pd.read_csv(wr_path+'8.csv')
wr9 = pd.read_csv(wr_path+'9.csv')
wr10 = pd.read_csv(wr_path+'10.csv')
wr11 = pd.read_csv(wr_path+'11.csv')
wr12 = pd.read_csv(wr_path+'12.csv')
wr13 = pd.read_csv(wr_path+'13.csv')
wr14 = pd.read_csv(wr_path+'14.csv')
wr15 = pd.read_csv(wr_path+'15.csv')
wr16 = pd.read_csv(wr_path+'16.csv')
wr17 = pd.read_csv(wr_path+'17.csv')

## TEs

In [7]:
te1 = pd.read_csv(te_path+'1.csv')
te2 = pd.read_csv(te_path+'2.csv')
te3 = pd.read_csv(te_path+'3.csv')
te4 = pd.read_csv(te_path+'4.csv')
te5 = pd.read_csv(te_path+'5.csv')
te6 = pd.read_csv(te_path+'6.csv')
te7 = pd.read_csv(te_path+'7.csv')
te8 = pd.read_csv(te_path+'8.csv')
te9 = pd.read_csv(te_path+'9.csv')
te10 = pd.read_csv(te_path+'10.csv')
te11 = pd.read_csv(te_path+'11.csv')
te12 = pd.read_csv(te_path+'12.csv')
te13 = pd.read_csv(te_path+'13.csv')
te14 = pd.read_csv(te_path+'14.csv')
te15 = pd.read_csv(te_path+'15.csv')
te16 = pd.read_csv(te_path+'16.csv')
te17 = pd.read_csv(te_path+'17.csv')

# Create list of weekly dataframes by position

In [8]:
qb_dfs = [qb1, qb2, qb3, qb4, qb5, qb6,
          qb7, qb8, qb9, qb10, qb11, qb12,
          qb13, qb14, qb15, qb16, qb17]

rb_dfs = [rb1, rb2, rb3, rb4, rb5, rb6,
          rb7, rb8, rb9, rb10, rb11, rb12,
          rb13, rb14, rb15, rb16, rb17]

wr_dfs = [wr1, wr2, wr3, wr4, wr5, wr6,
          wr7, wr8, wr9, wr10, wr11, wr12,
          wr13, wr14, wr15, wr16, wr17]

te_dfs = [te1, te2, te3, te4, te5, te6,
          te7, te8, te9, te10, te11, te12,
          te13, te14, te15, te16, te17]

# Add 'WK' column

In [9]:
for i in range(len(qb_dfs)):
    qb_dfs[i]['WK'] = i+1
    rb_dfs[i]['WK'] = i+1
    wr_dfs[i]['WK'] = i+1
    te_dfs[i]['WK'] = i+1

# Create one dataframe per position

In [10]:
qb = pd.concat(qb_dfs)
rb = pd.concat(rb_dfs)
wr = pd.concat(wr_dfs)
te = pd.concat(te_dfs)

# Clean up dataframes

## Drop rows with mostly NAs

In [11]:
qb = qb.dropna()
rb = rb.dropna()
wr = wr.dropna()
te = te.dropna()

## Drop unnecessary columns

In [12]:
qb = qb.drop(['G', 'FPTS/G', 'ROST'], axis=1)
rb = rb.drop(['G', 'FPTS/G', 'ROST'], axis=1)
wr = wr.drop(['G', 'FPTS/G', 'ROST'], axis=1)
te = te.drop(['G', 'FPTS/G', 'ROST'], axis=1)

## Remove teams from player names

In [13]:
for i in range(len(qb)):
    qb['Player'].iat[i] = qb['Player'].iat[i].split(' (', 1)[0]
    
for i in range(len(rb)):
    rb['Player'].iat[i] = rb['Player'].iat[i].split(' (', 1)[0]
    
for i in range(len(wr)):
    wr['Player'].iat[i] = wr['Player'].iat[i].split(' (', 1)[0]
    
for i in range(len(te)):
    te['Player'].iat[i] = te['Player'].iat[i].split(' (', 1)[0]

## Add in 0 pts for players in weeks where they don't appear

In [14]:
qb_players = qb['Player'].unique()
rb_players = rb['Player'].unique()
wr_players = wr['Player'].unique()
te_players = te['Player'].unique()

### First, remove players who only scored 0 points

In [15]:
no_point_qbs = []
no_point_rbs = []
no_point_wrs = []
no_point_tes = []

for qb_name in qb_players:
    if sum(qb[qb['Player'] == qb_name]['FPTS']) == 0:
        no_point_qbs.append(qb_name)
        
for rb_name in rb_players:
    if sum(rb[rb['Player'] == rb_name]['FPTS']) == 0:
        no_point_rbs.append(rb_name)
        
for wr_name in wr_players:
    if sum(wr[wr['Player'] == wr_name]['FPTS']) == 0:
        no_point_wrs.append(wr_name)
        
for te_name in te_players:
    if sum(te[te['Player'] == te_name]['FPTS']) == 0:
        no_point_tes.append(te_name)

In [16]:
qb = qb[~qb['Player'].isin(no_point_qbs)]
rb = rb[~rb['Player'].isin(no_point_rbs)]
wr = wr[~wr['Player'].isin(no_point_wrs)]
te = te[~te['Player'].isin(no_point_tes)]

### Now, add rows for players missing weeks

But we have to update the list of players since we just removed players who only ever scored 0 points

In [17]:
qb_players = qb['Player'].unique()
rb_players = rb['Player'].unique()
wr_players = wr['Player'].unique()
te_players = te['Player'].unique()

In [18]:
for i in range(n_weeks):
    
    # Insert rows for QBs missing weekly data
    for qb_name in qb_players:
        if i+1 not in pd.Series(qb[qb['Player'] == qb_name]['WK']).unique():
            qb.loc[len(qb.index)] = [999, qb_name, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, i+1]
            
    # Insert rows for RBs missing weekly data
    for rb_name in rb_players:
        if i+1 not in pd.Series(rb[rb['Player'] == rb_name]['WK']).unique():
            rb.loc[len(rb.index)] = [999, rb_name, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, i+1]

    # Insert rows for WRs missing weekly data
    for wr_name in wr_players:
        if i+1 not in pd.Series(wr[wr['Player'] == wr_name]['WK']).unique():
            wr.loc[len(wr.index)] = [999, wr_name, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, i+1]
    
    # Insert rows for TEs missing weekly data
    for te_name in te_players:
        if i+1 not in pd.Series(te[te['Player'] == te_name]['WK']).unique():
            te.loc[len(te.index)] = [999, te_name, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, i+1]

In [19]:
# Sort by week and then rank
qb = qb.sort_values(['WK', 'Rank', 'Player'])
rb = rb.sort_values(['WK', 'Rank', 'Player'])
wr = wr.sort_values(['WK', 'Rank', 'Player'])
te = te.sort_values(['WK', 'Rank', 'Player'])


# Resetting indexes
qb.reset_index(drop = True, inplace = True)
rb.reset_index(drop = True, inplace = True)
wr.reset_index(drop = True, inplace = True)
te.reset_index(drop = True, inplace = True)

# WAR

WAR stands for "Wins Above Replacement." The idea is to determine how many more/fewer wins a player contributed to their team relative to a replacement-level player. To do this, we need to figure out the following info:
1. Average weekly score in my league
2. Average team score standard deviation
3. Calculate replacement-level player for each position
4. Determine each player's WAR

## Average score and standard deviation

In [20]:
weekly_scores = pd.read_csv('C:\\Users\\Lenovo\\OneDrive\\Desktop\\fantasy_football\\2023\\LeagueScores.csv')
weekly_scores.head()

Week  HomeManagerID  HomeScore  AwayManagerID  AwayScore
0     1             11     113.00             10      94.82
1     1              6     135.82              5     114.66
2     1              7      50.26              2     114.66
3     1              8      83.30             12     119.40
4     1              1      96.12              9     127.18

In [21]:
home_scores = weekly_scores[['Week', 'HomeScore']].copy()
home_scores = home_scores.rename({'HomeScore': 'Score'}, axis=1)

away_scores = weekly_scores[['Week', 'AwayScore']].copy()
away_scores = away_scores.rename({'AwayScore': 'Score'}, axis=1)

all_scores = pd.concat([home_scores, away_scores])

In [22]:
all_scores.head()

Week   Score
0     1  113.00
1     1  135.82
2     1   50.26
3     1   83.30
4     1   96.12

In [23]:
weekly_avg = np.zeros(n_weeks)
weekly_std = np.zeros(n_weeks)

for i in range(n_weeks):
    weekly_avg[i] = all_scores[all_scores['Week'] == i+1]['Score'].mean()
    weekly_std[i] = all_scores[all_scores['Week'] == i+1]['Score'].std()

In [24]:
weekly_avg

array([104.86166667, 107.425     ,  95.95333333, 106.32      ,
       103.08333333,  95.64      ,  94.44833333, 118.57333333,
       102.00166667,  97.34833333, 103.84666667, 108.20666667,
       106.225     ,  99.81      , 107.73166667,  96.79166667,
        94.91666667])

In [25]:
weekly_std

array([23.88392606, 18.78185609, 16.01476667, 22.17908105, 23.36104735,
       23.75194078, 33.56761476, 24.00381535, 24.36761406, 21.30836534,
       28.73462825, 16.7278523 , 19.91837   , 16.79125422, 17.44121651,
       22.27822983, 22.2762488 ])

## Weekly replacement-level player by position

### QB

In [26]:
qb_replacements = qb[(qb['Rank'] > n_teams) & (qb['Rank'] <= n_teams*2)]
qb_starters = qb[qb['Rank'] <= n_teams]

In [27]:
qb_rep_score = np.zeros(n_weeks)

for i in range(n_weeks):
    qb_rep_score[i] = qb_replacements[qb_replacements['WK'] == i+1]['FPTS'].mean()

In [28]:
qb_rep_score

array([16.275     , 14.75833333, 14.675     , 15.13333333, 13.825     ,
       12.625     , 12.425     , 16.03333333, 12.54166667, 16.20833333,
       12.83333333, 15.41666667, 14.65833333, 12.85      , 13.85      ,
       13.05      , 12.46666667])

In [29]:
qb_exp_score = np.zeros(n_weeks)

for i in range(n_weeks):
    qb_exp_score[i] = qb_starters[qb_starters['WK'] == i+1]['FPTS'].mean()

In [30]:
qb_exp_score

array([24.16666667, 28.225     , 23.05      , 24.41666667, 22.8       ,
       22.26666667, 22.7       , 24.05833333, 23.21666667, 23.525     ,
       23.76666667, 24.76666667, 21.60833333, 23.90833333, 26.43333333,
       22.9       , 24.04166667])

### RB

In [31]:
rb_replacements = rb[(rb['Rank'] > n_teams*2) & (rb['Rank'] <= n_teams*4)]
rb_starters = rb[rb['Rank'] <= n_teams*2]

In [32]:
rb_rep_score = np.zeros(n_weeks)

for i in range(n_weeks):
    rb_rep_score[i] = rb_replacements[rb_replacements['WK'] == i+1]['FPTS'].mean()

In [33]:
rb_rep_score

array([7.6875    , 6.61666667, 7.03333333, 7.61666667, 7.62916667,
       4.78333333, 6.65416667, 7.45416667, 4.28333333, 5.89166667,
       5.41666667, 7.94166667, 6.775     , 4.9375    , 8.05833333,
       6.1875    , 6.9125    ])

In [34]:
rb_exp_score = np.zeros(n_weeks)

for i in range(n_weeks):
    rb_exp_score[i] = rb_starters[rb_starters['WK'] == i+1]['FPTS'].mean()

In [35]:
rb_exp_score

array([17.04583333, 13.67916667, 16.01666667, 18.62083333, 19.92083333,
       14.77916667, 18.14583333, 20.01666667, 16.17083333, 15.7875    ,
       16.14583333, 17.575     , 15.25833333, 15.9875    , 17.7125    ,
       16.13333333, 16.25      ])

### WR

In [36]:
wr_replacements = wr[(wr['Rank'] > n_teams*2) & (wr['Rank'] <= n_teams*4)]
wr_starters = wr[wr['Rank'] <= n_teams*2]

In [37]:
wr_rep_score = np.zeros(n_weeks)

for i in range(n_weeks):
    wr_rep_score[i] = wr_replacements[wr_replacements['WK'] == i+1]['FPTS'].mean()

In [38]:
wr_rep_score

array([ 9.75833333, 10.0875    , 10.64166667,  8.65833333,  8.74583333,
        8.61666667,  8.6375    ,  9.35416667,  5.7125    ,  9.52083333,
        8.65833333,  9.77916667,  9.27916667,  9.09583333,  9.54583333,
        8.96666667,  6.70833333])

In [39]:
wr_exp_score = np.zeros(n_weeks)

for i in range(n_weeks):
    wr_exp_score[i] = wr_starters[wr_starters['WK'] == i+1]['FPTS'].mean()

In [40]:
wr_exp_score

array([18.5375    , 21.12916667, 17.35      , 16.83333333, 17.1375    ,
       16.86666667, 16.31666667, 18.20416667, 15.4       , 18.5375    ,
       16.12916667, 17.37916667, 18.77916667, 17.        , 17.39166667,
       17.39583333, 16.77916667])

### TE

In [41]:
te_replacements = te[(te['Rank'] > n_teams) & (te['Rank'] <= n_teams*2)]
te_starters = te[te['Rank'] <= n_teams]

In [42]:
te_rep_score = np.zeros(n_weeks)

for i in range(n_weeks):
    te_rep_score[i] = te_replacements[te_replacements['WK'] == i+1]['FPTS'].mean()

In [43]:
te_rep_score

array([6.225     , 6.11666667, 6.03333333, 6.34166667, 6.04166667,
       6.93333333, 6.11666667, 6.5       , 5.25833333, 5.025     ,
       4.41666667, 5.95833333, 4.68333333, 3.78333333, 7.19166667,
       6.31666667, 8.4       ])

In [44]:
te_exp_score = np.zeros(n_weeks)

for i in range(n_weeks):
    te_exp_score[i] = te_starters[te_starters['WK'] == i+1]['FPTS'].mean()

In [45]:
te_exp_score

array([12.25      , 11.89166667, 13.04166667, 15.33333333, 14.61666667,
       13.725     , 11.05833333, 12.65      , 12.34166667, 11.59166667,
       12.63333333, 12.43333333, 10.05833333, 12.19166667, 14.425     ,
       16.48333333, 13.7       ])

### FLEX

This is a bit harder to calculate since the FLEX position could be a RB, WR, or TE. I'll assume the FLEX starters are the top 12-highest scores after the top 24 RBs, top 24 WRs, and top 12 TEs are removed, and the replacement-level FLEX players are the next 12 highest scorers.

In [46]:
rb_narrow = rb[['Rank', 'Player', 'FPTS', 'WK']].copy()
wr_narrow = wr[['Rank', 'Player', 'FPTS', 'WK']].copy()
te_narrow = te[['Rank', 'Player', 'FPTS', 'WK']].copy()

In [47]:
rb_narrow['POS'] = 'RB'
wr_narrow['POS'] = 'WR'
te_narrow['POS'] = 'TE'

In [48]:
flex = pd.concat([rb_narrow, wr_narrow, te_narrow])

In [49]:
flex.head()

Rank                 Player  FPTS  WK POS
0   1.0         Saquon Barkley  30.4   1  RB
1   2.0        Jonathan Taylor  25.5   1  RB
2   3.0          D'Andre Swift  25.0   1  RB
3   4.0  Cordarrelle Patterson  21.1   1  RB
4   5.0            Kareem Hunt  21.0   1  RB

In [50]:
# Removing starting RBs, WRs, and TEs
flex = flex[((flex['POS'] == 'RB') & (flex['Rank'] > 24)) |
            ((flex['POS'] == 'WR') & (flex['Rank'] > 24)) |
            ((flex['POS'] == 'TE') & (flex['Rank'] > 12))]

In [51]:
# Sorting points each week
flex = flex.sort_values(['WK', 'FPTS'], ascending=False)

In [52]:
# Updating rank calculations
flex['Rank'] = flex.groupby(['WK']).cumcount()+1

In [53]:
# Filtering down to replacement players
flex_replacements = flex[(flex['Rank'] > n_teams) & (flex['Rank'] <=n_teams*2)]
flex_starters = flex[flex['Rank'] <= n_teams]

In [54]:
flex_rep_score = np.zeros(n_weeks)

for i in range(n_weeks):
    flex_rep_score[i] = flex_replacements[flex_replacements['WK'] == i+1]['FPTS'].mean()

In [55]:
flex_rep_score

array([ 9.125     ,  8.925     , 10.01666667,  8.99166667,  8.89166667,
        7.775     ,  8.475     ,  9.20833333,  5.98333333,  8.625     ,
        8.04166667,  9.61666667,  8.7       ,  7.90833333,  9.91666667,
        8.54166667,  7.99166667])

In [56]:
flex_exp_score = np.zeros(n_weeks)

for i in range(n_weeks):
    flex_exp_score[i] = flex_starters[flex_starters['WK'] == i+1]['FPTS'].mean()

In [57]:
flex_exp_score

array([10.93333333, 11.4       , 11.95      , 10.11666667, 10.21666667,
       10.23333333, 10.375     , 10.23333333,  7.375     , 10.975     ,
        9.80833333, 11.275     , 10.45833333, 10.59166667, 11.21666667,
       10.46666667,  8.975     ])

## Individual Player WAR

### Defining functions

In [58]:
def collect_dataframes(player, position):
    """
    Return correct positional dataframes. This simplifies future coding by limiting the
    number of parameters that need to be passed in to the main function.
    """
    
    if position == 'QB':
        return (qb, qb_exp_score, qb_rep_score)
    
    elif position == 'RB':
        return (rb, rb_exp_score, rb_rep_score)
    
    elif position == 'WR':
        return (wr, wr_exp_score, wr_rep_score)
    
    else:
        return (te, te_exp_score, te_rep_score)

In [59]:
def get_player_exp_team_scores(player, position_df, exp_df, rep_df):
    """  
    Return the expected team scores by week for a player
    """
    
    # Create needed arrays
    player_scores = np.zeros(n_weeks)
    player_exp_team_scores = np.zeros(n_weeks)
    
    # Get player's scores for each week
    for i in range(n_weeks):
        player_scores[i] = position_df[(position_df['Player'] == player) & (position_df['WK'] == i+1)]['FPTS']
        
        # Replace 0s with replacement-level scores
        if player_scores[i] == 0:
            player_scores[i] = rep_df[i]
        
        player_exp_team_scores[i] = weekly_avg[i] - exp_df[i] + player_scores[i]
        
    return player_exp_team_scores

In [60]:
def get_player_win_prob(player_exp_team_scores):
    """
    Return the expected win probability for a team given that team's expected score
    """
    
    player_win_prob = np.zeros(n_weeks)
    player_z_score = (player_exp_team_scores - weekly_avg)/weekly_std
    
    for i in range(n_weeks):
        player_win_prob[i] = st.norm.cdf(player_z_score[i])
        
    return player_win_prob

In [61]:
def calculate_player_exp_wins(player, position):
    """
    Calculate the expected wins from a particular player assuming they start every week
    in which they are available.
    """
    
    # Get correct dataframes
    pos_df, exp_df, rep_df = collect_dataframes(player, position)
    
    # Get expected weekly scores with that player
    player_exp_team_scores = get_player_exp_team_scores(player, pos_df, exp_df, rep_df)
    
    # Get weekly win probability
    player_win_probs = get_player_win_prob(player_exp_team_scores)
    
    return sum(player_win_probs)

### Calculating replacement player exp. wins

In [62]:
rep_qb_exp_team_scores = weekly_avg - qb_exp_score + qb_rep_score
rep_rb_exp_team_scores = weekly_avg - rb_exp_score + rb_rep_score
rep_wr_exp_team_scores = weekly_avg - wr_exp_score + wr_rep_score
rep_te_exp_team_scores = weekly_avg - te_exp_score + te_rep_score
rep_flex_exp_team_scores = weekly_avg - flex_exp_score + flex_rep_score

In [63]:
rep_qb_win_prob = np.zeros(n_weeks)
rep_rb_win_prob = np.zeros(n_weeks)
rep_wr_win_prob = np.zeros(n_weeks)
rep_te_win_prob = np.zeros(n_weeks)
rep_flex_win_prob = np.zeros(n_weeks)

rep_qb_z_score = (rep_qb_exp_team_scores - weekly_avg)/weekly_std
rep_rb_z_score = (rep_rb_exp_team_scores - weekly_avg)/weekly_std
rep_wr_z_score = (rep_wr_exp_team_scores - weekly_avg)/weekly_std
rep_te_z_score = (rep_te_exp_team_scores - weekly_avg)/weekly_std
rep_flex_z_score = (rep_flex_exp_team_scores - weekly_avg)/weekly_std

for i in range(n_weeks):
    rep_qb_win_prob[i] = st.norm.cdf(rep_qb_z_score[i])
    rep_rb_win_prob[i] = st.norm.cdf(rep_rb_z_score[i])
    rep_wr_win_prob[i] = st.norm.cdf(rep_wr_z_score[i])
    rep_te_win_prob[i] = st.norm.cdf(rep_te_z_score[i])
    rep_flex_win_prob[i] = st.norm.cdf(rep_flex_z_score[i])

In [64]:
qb_rep_exp_wins = sum(rep_qb_win_prob)
rb_rep_exp_wins = sum(rep_rb_win_prob)
wr_rep_exp_wins = sum(rep_wr_win_prob)
te_rep_exp_wins = sum(rep_te_win_prob)
flex_rep_exp_wins = sum(rep_flex_win_prob)

print(f'Expected wins from replacement QB: {qb_rep_exp_wins:.3}')
print(f'Expected wins from replacement RB: {rb_rep_exp_wins:.3}')
print(f'Expected wins from replacement WR: {wr_rep_exp_wins:.3}')
print(f'Expected wins from replacement TE: {te_rep_exp_wins:.3}')
print(f'Expected wins from replacement FLEX: {flex_rep_exp_wins:.3}')

Expected wins from replacement QB: 5.51
Expected wins from replacement RB: 5.42
Expected wins from replacement WR: 5.86
Expected wins from replacement TE: 6.31
Expected wins from replacement FLEX: 7.93


### Getting individual WARs

In [65]:
flex_players = flex['Player'].unique()

qb_war = np.zeros(len(qb_players))
rb_war = np.zeros(len(rb_players))
wr_war = np.zeros(len(wr_players))
te_war = np.zeros(len(te_players))
flex_war = np.zeros(len(flex_players))

In [66]:
# Get QB WAR
for i in range(len(qb_war)):
    qb_war[i] = calculate_player_exp_wins(qb_players[i], 'QB') - qb_rep_exp_wins

# Get RB WAR
for i in range(len(rb_war)):
    rb_war[i] = calculate_player_exp_wins(rb_players[i], 'RB') - rb_rep_exp_wins
    
# Get WR WAR
for i in range(len(wr_war)):
    wr_war[i] = calculate_player_exp_wins(wr_players[i], 'WR') - wr_rep_exp_wins
    
# Get TE WAR
for i in range(len(te_war)):
    te_war[i] = calculate_player_exp_wins(te_players[i], 'TE') - te_rep_exp_wins

In [67]:
# Create function for formatting WAR dataframe

def generate_war_df(player_list, war_list):
    """
    Generate dataframe with player WAR sorting from largest to smallest
    """
    
    war_df = pd.DataFrame({'Player': player_list, 'WAR': war_list})
    war_df.reset_index(drop = True, inplace = True)
    
    return war_df.sort_values(['WAR'], ascending = False)   

In [68]:
qb_war_df = generate_war_df(qb_players, qb_war)
rb_war_df = generate_war_df(rb_players, rb_war)
wr_war_df = generate_war_df(wr_players, wr_war)
te_war_df = generate_war_df(te_players, te_war)

In [69]:
qb_war_df[:19]

Player       WAR
3          Jalen Hurts  3.348685
0   Patrick Mahomes II  3.270787
1           Josh Allen  3.114525
5           Joe Burrow  2.243945
22       Justin Fields  1.526355
23     Trevor Lawrence  1.452105
7        Lamar Jackson  1.445898
11        Kirk Cousins  1.371685
14          Geno Smith  1.369836
17          Jared Goff  1.160623
15        Daniel Jones  1.062850
21      Tua Tagovailoa  0.944493
8         Kyler Murray  0.941241
4       Justin Herbert  0.898214
30        Dak Prescott  0.868758
25           Tom Brady  0.835632
16          Derek Carr  0.437690
62         Sam Darnold  0.325448
9       Marcus Mariota  0.323119

In [70]:
rb_war_df[:50]

Player       WAR
27           Austin Ekeler  3.551306
17     Christian McCaffrey  3.464708
34             Josh Jacobs  3.210571
32           Derrick Henry  3.066843
0           Saquon Barkley  2.673317
13              Nick Chubb  2.485579
58            Tony Pollard  2.223313
19             Dalvin Cook  2.001031
10           Miles Sanders  1.879079
28             Aaron Jones  1.837390
55     Rhamondre Stevenson  1.738412
16            James Conner  1.726972
12         Jamaal Williams  1.647601
14       Leonard Fournette  1.571424
8                Joe Mixon  1.520925
47         Ezekiel Elliott  1.479490
25            Najee Harris  1.427968
120     Kenneth Walker III  1.279319
2            D'Andre Swift  1.226367
37      Travis Etienne Jr.  1.224946
46            Alvin Kamara  1.220204
43         Jerick McKinnon  1.217736
52           Dameon Pierce  1.176413
42        David Montgomery  1.054507
3    Cordarrelle Patterson  1.009563
1          Jonathan Taylor  0.980295
39             Breece Hall  0.977996
38        Devin Singletary  0.960590
9                AJ Dillon  0.913861
56          Raheem Mostert  0.781174
54         Jeff Wilson Jr.  0.767110
122        Latavius Murray  0.755020
75               Cam Akers  0.697180
11          Antonio Gibson  0.675290
102         Tyler Allgeier  0.663163
5    Clyde Edwards-Helaire  0.622843
89      Brian Robinson Jr.  0.621937
21          Khalil Herbert  0.594796
48           Samaje Perine  0.585344
76            J.K. Dobbins  0.521543
71          D'Onta Foreman  0.457018
7           James Robinson  0.452880
20           Isiah Pacheco  0.394396
59           Rachaad White  0.316198
108         Zonovan Knight  0.248925
35           Rashaad Penny  0.237864
41           Damien Harris  0.191574
45       Melvin Gordon III  0.185971
49            Kenyan Drake  0.176999
140          Tevin Coleman  0.139508

In [71]:
wr_war_df[:50]

Player       WAR
0       Justin Jefferson  2.908673
20           Tyreek Hill  2.433818
2          Davante Adams  2.195914
6             A.J. Brown  1.883426
5           Stefon Diggs  1.843313
74           CeeDee Lamb  1.676818
13     Amon-Ra St. Brown  1.478540
1            Cooper Kupp  1.468216
3          Ja'Marr Chase  1.315765
14         Jaylen Waddle  1.314111
155        DeVonta Smith  1.281548
76           Tee Higgins  1.114160
84          Amari Cooper  1.005530
73         Tyler Lockett  0.941623
65          Chris Godwin  0.851363
15            Mike Evans  0.813972
64            DK Metcalf  0.750202
18        Christian Kirk  0.735432
206      DeAndre Hopkins  0.674923
34             Zay Jones  0.647948
101        Mike Williams  0.638256
10           Jerry Jeudy  0.600443
24        Terry McLaurin  0.572727
51        Garrett Wilson  0.570274
59         Brandon Aiyuk  0.567600
43          Keenan Allen  0.537488
4    Michael Pittman Jr.  0.472451
54              DJ Moore  0.462998
27          Deebo Samuel  0.419726
48           Chris Olave  0.410054
25        Marquise Brown  0.397285
62      Christian Watson  0.393733
46         Jakobi Meyers  0.366617
12          Jahan Dotson  0.297997
11            Gabe Davis  0.224480
7         Michael Thomas  0.204598
41   JuJu Smith-Schuster  0.142095
22          DJ Chark Jr.  0.134655
189         Allen Lazard  0.132993
29            Tyler Boyd  0.076690
142       Isaiah Hodgins  0.068200
36      Courtland Sutton  0.066962
37    Mecole Hardman Jr.  0.066412
63          Adam Thielen  0.065015
147        Rondale Moore  0.057645
16         Curtis Samuel  0.036785
184     Jameson Williams -0.009877
23        Rashod Bateman -0.011535
100         Mack Hollins -0.017936
162         Jalen Nailor -0.025638

In [72]:
te_war_df[:20]

Player       WAR
0         Travis Kelce  2.757661
20      T.J. Hockenson  1.351461
11        Mark Andrews  1.271725
100      George Kittle  1.133091
9       Dalton Schultz  0.755018
2          Taysom Hill  0.749769
25         Evan Engram  0.747303
12      Dallas Goedert  0.660356
7       Pat Freiermuth  0.600888
6            Zach Ertz  0.557644
50         Dawson Knox  0.541048
44         David Njoku  0.535621
22       Juwan Johnson  0.531164
16        Tyler Higbee  0.514397
72           Cole Kmet  0.416813
8        Darren Waller  0.383922
3       Gerald Everett  0.325351
10       Tyler Conklin  0.227201
94        Greg Dulcich  0.195897
43   Chigoziem Okonkwo  0.098508

## League-wide WAR

In [73]:
qb_war_df['POS'] = 'QB'
rb_war_df['POS'] = 'RB'
wr_war_df['POS'] = 'WR'
te_war_df['POS'] = 'TE'

league_war = pd.concat([qb_war_df, rb_war_df, wr_war_df, te_war_df])

In [75]:
league_war = league_war.sort_values(['WAR'], ascending = False)
league_war.reset_index(drop = True, inplace = True)
league_war[:50]

Player       WAR POS
0         Austin Ekeler  3.551306  RB
1   Christian McCaffrey  3.464708  RB
2           Jalen Hurts  3.348685  QB
3    Patrick Mahomes II  3.270787  QB
4           Josh Jacobs  3.210571  RB
5            Josh Allen  3.114525  QB
6         Derrick Henry  3.066843  RB
7      Justin Jefferson  2.908673  WR
8          Travis Kelce  2.757661  TE
9        Saquon Barkley  2.673317  RB
10           Nick Chubb  2.485579  RB
11          Tyreek Hill  2.433818  WR
12           Joe Burrow  2.243945  QB
13         Tony Pollard  2.223313  RB
14        Davante Adams  2.195914  WR
15          Dalvin Cook  2.001031  RB
16           A.J. Brown  1.883426  WR
17        Miles Sanders  1.879079  RB
18         Stefon Diggs  1.843313  WR
19          Aaron Jones  1.837390  RB
20  Rhamondre Stevenson  1.738412  RB
21         James Conner  1.726972  RB
22          CeeDee Lamb  1.676818  WR
23      Jamaal Williams  1.647601  RB
24    Leonard Fournette  1.571424  RB
25        Justin Fields  1.526355  QB
26            Joe Mixon  1.520925  RB
27      Ezekiel Elliott  1.479490  RB
28    Amon-Ra St. Brown  1.478540  WR
29          Cooper Kupp  1.468216  WR
30      Trevor Lawrence  1.452105  QB
31        Lamar Jackson  1.445898  QB
32         Najee Harris  1.427968  RB
33         Kirk Cousins  1.371685  QB
34           Geno Smith  1.369836  QB
35       T.J. Hockenson  1.351461  TE
36        Ja'Marr Chase  1.315765  WR
37        Jaylen Waddle  1.314111  WR
38        DeVonta Smith  1.281548  WR
39   Kenneth Walker III  1.279319  RB
40         Mark Andrews  1.271725  TE
41        D'Andre Swift  1.226367  RB
42   Travis Etienne Jr.  1.224946  RB
43         Alvin Kamara  1.220204  RB
44      Jerick McKinnon  1.217736  RB
45        Dameon Pierce  1.176413  RB
46           Jared Goff  1.160623  QB
47        George Kittle  1.133091  TE
48          Tee Higgins  1.114160  WR
49         Daniel Jones  1.062850  QB